# Generated by Django 5.0.4 on 2024-05-02 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
