# Generated by Django 5.0.4 on 2024-05-02 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0002_search_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="last_viewed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
